### ISSUE TITLE
Running postgres example docker failing

### ISSUE THREAD

**Issue by idkjs** [aantron/dream#154]
FYI, running the postgres example in docker container is failing with following output. I will try to debug it when I get a second if you dont first.

```sh
~/Github/DREAM/dream-w-postgres                                                                                                       ✘ 255  3.0.1
❯ docker-compose build
postgres uses an image, skipping
Building web
[+] Building 49.2s (11/18)                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                          0.0s
 => => transferring dockerfile: 703B                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                             0.0s
 => => transferring context: 259B                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/debian:stable-slim                                                                         2.0s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                 0.0s
 => [internal] load build context                                                                                                             0.0s
 => => transferring context: 6.99kB                                                                                                           0.0s
 => [run 1/4] FROM docker.io/library/debian:stable-slim@sha256:a85c2c0e634946e92a6f4a9a4f6ce5f19ce7c11885bc198f04ab3ae8dacbaffa               4.1s
 => => resolve docker.io/library/debian:stable-slim@sha256:a85c2c0e634946e92a6f4a9a4f6ce5f19ce7c11885bc198f04ab3ae8dacbaffa                   0.0s
 => => sha256:697241766016756fd3200ed8914ace4be1db121300ea9348431f1abdb928aff8 1.48kB / 1.48kB                                                0.0s
 => => sha256:009cb70223803630c3d1c139514e8d49ecd2176a5054b977ed7fdf98f8e96e60 25.91MB / 25.91MB                                              3.3s
 => => sha256:a85c2c0e634946e92a6f4a9a4f6ce5f19ce7c11885bc198f04ab3ae8dacbaffa 1.85kB / 1.85kB                                                0.0s
 => => sha256:059c42f4ffa41c66aeaabf43821e16429b31e090e9f86e08bda8b2282a9e6876 529B / 529B                                                    0.0s
 => => extracting sha256:009cb70223803630c3d1c139514e8d49ecd2176a5054b977ed7fdf98f8e96e60                                                     0.7s
 => [run 2/4] RUN apt-get update                                                                                                              2.7s
 => [build  3/11] RUN apt-get install -y curl git libpq-dev m4 npm unzip                                                                     28.7s
 => [run 3/4] RUN apt-get install -y libev4 libpq5 libssl1.1                                                                                  1.9s
 => [build  4/11] WORKDIR /build                                                                                                              0.0s
 => ERROR [build  5/11] RUN npm install esy                                                                                                  11.6s
------
 > [build  5/11] RUN npm install esy:
#10 0.476 npm WARN npm npm does not support Node.js v10.24.0
#10 0.476 npm WARN npm You should probably upgrade to a newer version of node as we
#10 0.476 npm WARN npm can't make any promises that npm will work with this version.
#10 0.476 npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
#10 0.476 npm WARN npm You can find the latest version at https://nodejs.org/
#10 11.14 
#10 11.14 > esy@0.6.11 postinstall /build/node_modules/esy
#10 11.14 > node -e "process.env['OCAML_VERSION'] = process.platform == 'linux' ? '4.12.0-musl.static.flambda': '4.12.0'; process.env['OCAML_PKG_NAME'] = 'ocaml'; require('./postinstall.js')"
#10 11.14 
#10 11.40 fs.js:114
#10 11.40     throw err;
#10 11.40     ^
#10 11.40 
#10 11.40 Error: ENOENT: no such file or directory, scandir '/build/node_modules/esy/platform-linux-arm64/bin'
#10 11.40     at Object.readdirSync (fs.js:790:3)
#10 11.40     at copyRecursive (/build/node_modules/esy/postinstall.js:28:17)
#10 11.40     at foldersToCopy.forEach.folderPath (/build/node_modules/esy/postinstall.js:138:5)
#10 11.40     at Array.forEach (<anonymous>)
#10 11.40     at copyPlatformBinaries (/build/node_modules/esy/postinstall.js:134:17)
#10 11.40     at Object.<anonymous> (/build/node_modules/esy/postinstall.js:172:5)
#10 11.40     at Module._compile (internal/modules/cjs/loader.js:778:30)
#10 11.40     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#10 11.40     at Module.load (internal/modules/cjs/loader.js:653:32)
#10 11.40     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
#10 11.42 npm WARN enoent ENOENT: no such file or directory, open '/build/package.json'
#10 11.42 npm WARN build No description
#10 11.42 npm WARN build No repository field.
#10 11.42 npm WARN build No README data
#10 11.42 npm WARN build No license field.
#10 11.42 
#10 11.42 npm ERR! code ELIFECYCLE
#10 11.42 npm ERR! errno 1
#10 11.42 npm ERR! esy@0.6.11 postinstall: `node -e "process.env['OCAML_VERSION'] = process.platform == 'linux' ? '4.12.0-musl.static.flambda': '4.12.0'; process.env['OCAML_PKG_NAME'] = 'ocaml'; require('./postinstall.js')"`
#10 11.42 npm ERR! Exit status 1
#10 11.42 npm ERR! 
#10 11.42 npm ERR! Failed at the esy@0.6.11 postinstall script.
#10 11.42 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#10 11.57 
#10 11.57 npm ERR! A complete log of this run can be found in:
#10 11.57 npm ERR!     /root/.npm/_logs/2021-08-11T14_54_01_492Z-debug.log
------
executor failed running [/bin/sh -c npm install esy]: exit code: 1
ERROR: Service 'web' failed to build : Build failed

~/Github/DREAM/dream-w-postgres                                                                                                         49s  3.0.1
❯ 
```

**Comment by aantron** [comment]
This is probably an instance of https://github.com/esy/esy/issues/1308.

**Comment by idkjs** [comment]
@aantron i guess same goes for rest of docker files in this repo?

**Comment by aantron** [comment]
Does esy work outside Docker for you?

**Comment by idkjs** [comment]
Yes.

**Comment by aantron** [comment]
@idkjs Can you give details on what system you are on?

@EduardoRFS, could you comment on this issue?

**Comment by idkjs** [comment]
```sh
❯ sw_vers
ProductName:    macOS
ProductVersion: 11.5
BuildVersion:   20G71

~/Github/auth-service feature/remove-pesy                                                                                                    3.0.1
❯ docker --version
Docker version 20.10.7, build f0df350
```

**Comment by aantron** [comment]
Can you clearly show the processor architecture as well?

**Comment by aantron** [comment]
Great, thanks @EduardoRFS!

@idkjs I suggest to watch https://github.com/esy/esy/issues/1308 for updates, and probably await the next release of esy.

We could also take the Dream server out of Docker in that example, and run it directly on the host machine. There is no fundamental reason why it needs to be Dockerized. It would, however, be less convenient than just using Docker Compose to "run the whole setup," so I'm not committed to doing that.

Another near-term option is to try an opam build in Docker, as in the [Docker opam example](https://github.com/aantron/dream/blob/master/example/z-docker-opam/Dockerfile).

**Comment by idkjs** [comment]
works without docker here ->https://github.com/idkjs/dream-examples/tree/main/dream-w-postgres
