### ISSUE TITLE
r-fullstack-melange fails to compile 

### ISSUE THREAD

**Issue by unoexperto** [aantron/dream#293]
Hi folks,

Could you please advise what I'm missing ?

```
~/work/sideprojects/ocaml/dream/example/r-fullstack-melange$ npm install                                                                                                       
npm WARN deprecated bs-webapi@0.19.1: Use https://www.npmjs.com/package/rescript-webapi
npm ERR! code 1
npm ERR! path /home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! node:internal/fs/utils:351
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: ENOENT: no such file or directory, scandir '/home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/platform-linux/bin'
npm ERR!     at Object.readdirSync (node:fs:1543:3)
npm ERR!     at copyRecursive (/home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/postinstall.js:28:17)
npm ERR!     at /home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/postinstall.js:131:5
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at copyPlatformBinaries (/home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/postinstall.js:127:17)
npm ERR!     at Object.<anonymous> (/home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/postinstall.js:162:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1233:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1091:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:938:12) {
npm ERR!   errno: -2,
npm ERR!   syscall: 'scandir',
npm ERR!   code: 'ENOENT',
npm ERR!   path: '/home/expert/work/sideprojects/ocaml/dream/example/r-fullstack-melange/node_modules/bsdoc/platform-linux/bin'
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.5.1

npm ERR! A complete log of this run can be found in: /home/expert/.npm/_logs/2023-08-13T15_12_04_438Z-debug-0.log

```

**Comment by aantron** [comment]
Hi! The [above commit](https://github.com/aantron/dream/commit/e570114299c3886429d4319e2308c5f3d48e72b8) updates the [Melange example](https://github.com/aantron/dream/tree/master/example/r-fullstack-melange#files) to use the latest version of Melange, which likely doesn't have the issue you've reported (thanks!).
